### ISSUE TITLE
error while loading the new Openmotics integration

### ISSUE THREAD

**Issue by DCL777** [woutercoppens/home-assistant#1]
## Version of the custom_component
main repo: 11 days old

## Configuration

nothing yet configured

## Describe the bug
Hi  Wouter,

I followed the manual to install your integration and used "Option 1: Copy Method" because the HACS method gave me an error while adding the new repo.
(HACS 1.16.0, front end version: 20211010111104)
![image](https://user-images.githubusercontent.com/55956951/140800397-98b08d6c-68fe-4d3f-af0b-7a4650931004.png)

after shutting HA down and restarted it, i started the new Openmotics Integration.
After a while (1-2 min.) i received the following error:
![image](https://user-images.githubusercontent.com/55956951/140799641-f934cb61-2f00-4177-b182-d1322fae6a0a.png)

Do you know, what could be wrong?
is there somewhere a log file that i can provide you?

Thanks a lot

kind regards,
Dries

## Debug log

not yet available, do you have the exact name? 
```
logger:
  default: critical
  logs:
    homeassistant.components.openmotics: info
```    
is this correct?

**Comment by woutercoppens** [comment]
**Debug log**
```
logger:
  default: warning
  #default: debug
  logs:
    custom_components.openmotics: debug
```

! Be careful about the intents !
